### ISSUE TITLE
GD-343: GdUnit4 unload issues when using Godot Mono `.NET: Failed to unload assemblies.`

### ISSUE THREAD

**Issue by MikeSchulze** [MikeSchulze/gdUnit4#343]
### The used GdUnit4 version

4.2.0 (Latest Release)

### The used Godot version

v4.2.1.stable.mono.official [b09f793f5]

### Operating System

Windows 11, MacOS

### Describe the bug

Some GdUnit4 users reported these errors on discord -> https://discordapp.com/channels/885149082119733269/1201435634875764756

```
 /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:112 - System.ArgumentException: An item with the same key has already been added. Key: GdUnit4.GdUnit4MonoAPI
     at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
     at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
     at Godot.Bridge.ScriptManagerBridge.ScriptTypeBiMap.Add(IntPtr scriptPtr, Type scriptType) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.types.cs:line 23
     at Godot.Bridge.ScriptManagerBridge.TryReloadRegisteredScriptWithClass(IntPtr scriptPtr) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:line 587
  modules/mono/mono_gd/gd_mono.cpp:528 - .NET: Failed to unload assemblies. Please check https://github.com/godotengine/godot/issues/78513 for more information. (User)
  modules/mono/mono_gd/gd_mono.cpp:528 
  modules/mono/mono_gd/gd_mono.cpp:528 
  modules/mono/mono_gd/gd_mono.cpp:512 
  modules/mono/mono_gd/gd_mono.cpp:528 
  ```

### Steps to Reproduce

Example:
* Create a project and add the GdUnit4 plugin.
* make some changes in your C# classes and recreate the project
these errors occur randomly

**Comment by Alia5** [comment]
I still have this issue with the nwest version of GdUnit / Gdunit4Net.  
The issue appears **always** and not randomly

**Comment by MikeSchulze** [comment]
> I still have this issue with the nwest version of GdUnit / Gdunit4Net. The issue appears **always** and not randomly

Hi @Alia5 , that's bad to hear, can you please open a new issue and attach the exception.
If you are able to reproduce, do also add an example project for deeper investigation.
